import Vue from 'vue';
import Vuetify, {
	VApp,
	VNavigationDrawer,
	VToolbar,
	VContent,
	VFooter,
	VProgressLinear,
	VList,
	VListItem,
	VListItemAction,
	VListItemContent,
	VListItemTitle,
	VIcon,
	VDivider,
	VSubheader,
	VToolbarTitle,
	VSpacer,
	VContainer,
	VLayout,
	VFlex,
	VAlert,
	VDataTable,
	VCheckbox,
	VCardTitle,
	VTextField,
	VSwitch,
	VExpansionPanel,
	VExpansionPanels,
	VExpansionPanelContent,
	VExpansionPanelHeader,
	VSlideYTransition,
	VFadeTransition,
	VBtn,
	VCard,
	VCardActions,
	VCardText,
	VMenu,
	VDatePicker,
	VForm,
	VSnackbar,
	VProgressCircular,
	VDialog,
	VSelect,
	VTextarea,
	VAppBar,
	VAppBarNavIcon,
	VRow,
	VCol,
} from 'vuetify/lib';
// @ts-ignore
import { Ripple, Touch } from 'vuetify/lib/directives';

import colors from 'vuetify/lib/util/colors';
import ru from 'vuetify/src/locale/ru';

Vue.use(Vuetify, {
	components: {
		VApp,
		VNavigationDrawer,
		VToolbar,
		VContent,
		VFooter,
		VProgressLinear,
		VIcon,
		VList,
		VListItem,
		VListItemAction,
		VListItemContent,
		VListItemTitle,
		VDivider,
		VSubheader,
		VToolbarTitle,
		VSpacer,
		VContainer,
		VLayout,
		VFlex,
		VAlert,
		VDataTable,
		VCheckbox,
		VCardTitle,
		VTextField,
		VSwitch,
		VExpansionPanel,
		VExpansionPanels,
		VExpansionPanelContent,
		VExpansionPanelHeader,
		VSlideYTransition,
		VFadeTransition,
		VBtn,
		VCard,
		VCardActions,
		VCardText,
		VMenu,
		VDatePicker,
		VForm,
		VSnackbar,
		VProgressCircular,
		VDialog,
		VSelect,
		VTextarea,
		VAppBar,
		VAppBarNavIcon,
		VRow,
		VCol,

	},
	directives: {
		Ripple,
		Touch,
	},
});

const vuetify = new Vuetify({
	icons: {
		iconfont: 'fa4',
	},
	locale: {
		current: 'ru',
		locales: { ru },
	},
	theme: {
		dark: false,
		themes: {
			light: {
				primary: colors.lightBlue.base,
				secondary: colors.deepPurple.accent1,
				accent: colors.deepOrange.base,
				error: colors.red.base,
				warning: colors.amber.base,
				info: colors.cyan.base,
				success: colors.green.darken1,
			},
			dark: {
				primary: colors.blue.darken2,
				secondary: colors.deepPurple.base,
				accent: colors.amber.darken2,
				error: colors.red.base,
				warning: colors.amber.base,
				info: colors.cyan.base,
				success: colors.green.darken1,
			},
		},
	},
});
export default vuetify;
