// <auto-generated />
using System;
using Dns.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Dns.DAL.Migrations
{
    [DbContext(typeof(DnsDbContext))]
    [Migration("20191002201634_AddLastUpdateField")]
    partial class AddLastUpdateField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:citext", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:dblink", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Dns.DAL.Models.AttackGroupHistories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AttackGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamptz");

                    b.Property<int>("PrevStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttackGroupId");

                    b.HasIndex("Id")
                        .HasName("IX_AttackGroupHistories_Id");

                    b.ToTable("GroupHistories");
                });

            modelBuilder.Entity("Dns.DAL.Models.AttackGroups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("DateBegin")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DateClose")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasName("IX_AttackGroups_Id");

                    b.ToTable("AttackGroups");
                });

            modelBuilder.Entity("Dns.DAL.Models.AttackHistories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AttackId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamptz");

                    b.Property<int>("PrevStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttackId");

                    b.HasIndex("Id")
                        .HasName("IX_AttackHistories_Id");

                    b.ToTable("AttackHistories");
                });

            modelBuilder.Entity("Dns.DAL.Models.AttackNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AttackGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Text")
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("AttackGroupId");

                    b.HasIndex("Id")
                        .HasName("IX_AttackNotes_Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Dns.DAL.Models.Attacks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AttackGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("BlackDomain")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("character varying(45)")
                        .HasMaxLength(45);

                    b.Property<bool>("IpBlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubnetBlocked")
                        .HasColumnType("character varying(18)")
                        .HasMaxLength(18);

                    b.Property<string>("WhiteDomain")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("AttackGroupId");

                    b.HasIndex("BlackDomain")
                        .HasName("IX_Attacks_BlackDomain");

                    b.HasIndex("Id")
                        .HasName("IX_Attacks_Id");

                    b.HasIndex("Ip")
                        .HasName("IX_Attacks_Ip");

                    b.HasIndex("Status")
                        .HasName("IX_Attacks_Status");

                    b.HasIndex("WhiteDomain")
                        .HasName("IX_Attacks_WhiteDomain");

                    b.ToTable("DnsAttacks");
                });

            modelBuilder.Entity("Dns.DAL.Models.DomainExcludedNames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BlackDomain")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("WhiteDomain")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("BlackDomain")
                        .HasName("IX_DomainExcludedNames_BlackDomain");

                    b.HasIndex("Id")
                        .HasName("IX_DomainExcludedNames_Id");

                    b.HasIndex("WhiteDomain")
                        .HasName("IX_DomainExcludedNames_WhiteDomain");

                    b.ToTable("DomainExcludedNames");
                });

            modelBuilder.Entity("Dns.DAL.Models.DomainInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateCreate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DateUntil")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Registrant")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasName("IX_DomainInfo_Domain");

                    b.HasIndex("Id")
                        .HasName("IX_DomainInfo_Id");

                    b.ToTable("DomainInfo");
                });

            modelBuilder.Entity("Dns.DAL.Models.DomainNSs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DomainId")
                        .HasColumnType("integer");

                    b.Property<int>("NsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("Id")
                        .HasName("IX_DomainNSs_Id");

                    b.HasIndex("NsId");

                    b.ToTable("DomainNs");
                });

            modelBuilder.Entity("Dns.DAL.Models.IpInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("character varying(45)")
                        .HasMaxLength(45);

                    b.Property<string>("Subnet")
                        .HasColumnType("character varying(18)")
                        .HasMaxLength(18);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasName("IX_IpInfo_Id");

                    b.HasIndex("Ip")
                        .IsUnique()
                        .HasName("IX_IpInfo_Ip");

                    b.ToTable("IpInfo");
                });

            modelBuilder.Entity("Dns.DAL.Models.NameServers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NameServer")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasName("IX_NameServers_Id");

                    b.ToTable("NameServers");
                });

            modelBuilder.Entity("Dns.DAL.Models.StatisticHistories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AttackComplete")
                        .HasColumnType("integer");

                    b.Property<int>("AttackIntersection")
                        .HasColumnType("integer");

                    b.Property<int>("AttackNew")
                        .HasColumnType("integer");

                    b.Property<int>("AttackTotal")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamptz");

                    b.Property<int>("GroupAttack")
                        .HasColumnType("integer");

                    b.Property<int>("GroupComplete")
                        .HasColumnType("integer");

                    b.Property<int>("GroupDynamic")
                        .HasColumnType("integer");

                    b.Property<int>("GroupNew")
                        .HasColumnType("integer");

                    b.Property<int>("GroupThreat")
                        .HasColumnType("integer");

                    b.Property<int>("GroupTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasName("IX_StatisticHistories_Date");

                    b.HasIndex("Id")
                        .HasName("IX_StatisticHistories_Id");

                    b.ToTable("StatisticHistories");
                });

            modelBuilder.Entity("Dns.DAL.Models.SuspectDomains", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_SuspectDomain_Id");

                    b.ToTable("SuspectDomains");
                });

            modelBuilder.Entity("Dns.DAL.Models.WhiteDomains", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasName("IX_WhiteDomains_Domain");

                    b.HasIndex("Id")
                        .HasName("IX_WhiteDomains_Id");

                    b.ToTable("WhiteDomains");
                });

            modelBuilder.Entity("Dns.DAL.Models.AttackGroupHistories", b =>
                {
                    b.HasOne("Dns.DAL.Models.AttackGroups", "AttackGroup")
                        .WithMany("GroupHistories")
                        .HasForeignKey("AttackGroupId")
                        .HasConstraintName("FK_AttackGroupHistories_AttackGroups_AttackGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dns.DAL.Models.AttackHistories", b =>
                {
                    b.HasOne("Dns.DAL.Models.Attacks", "Attack")
                        .WithMany("Histories")
                        .HasForeignKey("AttackId")
                        .HasConstraintName("FK_AttackHistories_Attacks_AttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dns.DAL.Models.AttackNotes", b =>
                {
                    b.HasOne("Dns.DAL.Models.AttackGroups", "AttackGroup")
                        .WithMany("Notes")
                        .HasForeignKey("AttackGroupId")
                        .HasConstraintName("FK_AttackNotes_AttackGroups_AttackGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dns.DAL.Models.Attacks", b =>
                {
                    b.HasOne("Dns.DAL.Models.AttackGroups", "AttackGroup")
                        .WithMany("Attacks")
                        .HasForeignKey("AttackGroupId")
                        .HasConstraintName("FK_Attacks_AttackGroups_AttackGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dns.DAL.Models.DomainNSs", b =>
                {
                    b.HasOne("Dns.DAL.Models.DomainInfo", "Domain")
                        .WithMany("DomainNS")
                        .HasForeignKey("DomainId")
                        .HasConstraintName("FK_DomainNSs_DomainInfo_DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dns.DAL.Models.NameServers", "NameServer")
                        .WithMany("DomainNS")
                        .HasForeignKey("NsId")
                        .HasConstraintName("FK_DomainNSs_NameServers_NsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
